--  CREATE TABLE
CREATE TABLE TC_ROL
(
    ID INT AUTO_INCREMENT COMMENT 'IDENTIFICADOR UNICO CONSECUTIVO DE ROLES', 
    ROL VARCHAR(20) UNIQUE NOT NULL COMMENT 'NOMBRE DEL ROL', 
    ESTATUS INT DEFAULT 1 COMMENT 'ESTADOS DEL ROL 0: BORRADO, 1: ACTIVO 2: FUERA DE SERVICIO',
    UM VARCHAR(20) NOT NULL COMMENT 'USUARIO QUE REALIZO EL ÚLTIMO MOVIMIENTO',
    FM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT 'FECHA EN QUE SE REALIZO EL ULTIMO MOVIMIENTO',
    PRIMARY KEY (ID)
) 
COMMENT = 'CATALOGO DE ROLES';
--  CREATE UNIQUE INDEX
CREATE UNIQUE INDEX PK_ROLE_ID ON TC_ROL (ID);
CREATE UNIQUE INDEX UK_ROLE_ROL ON TC_ROL (ROL);
--  CREATE BITACORA
CREATE TABLE TB_ROL
(
    ID INT COMMENT 'IDENTIFICADOR UNICO CONSECUTIVO DE ROLES', 
    ROL VARCHAR(20) COMMENT 'NOMBRE DEL ROL', 
    ESTATUS INT COMMENT 'ESTADOS DEL DEL ROL 0: BORRADO, 1: ACTIVO 2: FUERA DE SERVICIO',
    UM VARCHAR(20) COMMENT 'USUARIO QUE REALIZO EL ÚLTIMO MOVIMIENTO',
    FM TIMESTAMP COMMENT 'FECHA EN QUE SE REALIZO EL ULTIMO MOVIMIENTO',
    TIPO_CAMBIO VARCHAR(40) COMMENT 'MOVIMIENTO QUE SE HIZO'
) 
COMMENT = 'BITACORA DE ROLES';

DELIMITER //
CREATE TRIGGER TGR_B_ROLE_INSERT BEFORE INSERT ON TC_ROL
FOR EACH ROW
BEGIN
    DECLARE V_TIPO_CAMBIO VARCHAR(6);

    IF NEW.ID IS NOT NULL THEN
        -- No es necesario verificar si es NULL en MariaDB
        SET V_TIPO_CAMBIO = 'INSERT';
    END IF;

    INSERT INTO TB_ROL
        (ID, ROL, ESTATUS, UM, FM, TIPO_CAMBIO)
    VALUES
        (
            NEW.ID,
            NEW.ROL,
            NEW.ESTATUS,
            NEW.UM,
            NEW.FM,
            V_TIPO_CAMBIO
        );
END;
//
CREATE TRIGGER TGR_B_ROLE_UPDATE BEFORE UPDATE ON TC_ROL
FOR EACH ROW
BEGIN
    DECLARE V_TIPO_CAMBIO VARCHAR(6);
    IF NEW.ID IS NOT NULL THEN
        IF NEW.ROL <=> OLD.ROL THEN
            SET V_TIPO_CAMBIO = 'UPDATE';
        END IF;
    END IF;
    INSERT INTO TB_ROL
        (ID, ROL, ESTATUS, UM, FM, TIPO_CAMBIO)
    VALUES
        (
            NEW.ID,
            NEW.ROL,
            NEW.ESTATUS,
            NEW.UM,
            NEW.FM,
            V_TIPO_CAMBIO
        );
END;
//
CREATE TRIGGER TGR_B_ROLE_DELETE BEFORE DELETE ON TC_ROL
FOR EACH ROW
BEGIN
    DECLARE V_TIPO_CAMBIO VARCHAR(6);
    SET V_TIPO_CAMBIO = 'DELETE';
    INSERT INTO TB_ROL
        (ID, ROL, ESTATUS, UM, FM, TIPO_CAMBIO)
    VALUES
        (
            OLD.ID,
            OLD.ROL,
            OLD.ESTATUS,
            OLD.UM,
            OLD.FM,
            V_TIPO_CAMBIO
        );
END;
//
DELIMITER ;
